{% set name = "h3pandas" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/h3pandas-{{ version }}.tar.gz
  sha256: caf51e93190a6f8af8aab4645aaa4a29f5336d07697c24179bacb6c90bd48a9f


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - geopandas =0.9.*
    - h3-py =3.7.*
    - numpy
    - pandas
    - python >=3.6
    - shapely
    - typing-extensions

test:
  imports:
    - h3pandas
    - h3pandas.util
  commands:
    - pytest --pyargs h3pandas
  requires:
    - pytest

about:
  home: https://github.com/DahnJ/H3-Pandas
  summary: Integration of H3 and GeoPandas
  license: MIT
  license_file: LICENSE
  doc_url: https://h3-pandas.readthedocs.io/en/latest/
  dev_url: https://github.com/DahnJ/H3-Pandas

extra:
  recipe-maintainers:
    - dahn
