{% set name = "h3pandas" %}
{% set version = "0.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/h3pandas-{{ version }}.tar.gz
  sha256: 78d83b4c39ce08672f1c710dbafdb3d5b06fa33af54e72f081d3f2566fb7936f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - geopandas
    - h3-py
    - numpy
    - pandas
    - python >=3.8
    - shapely
    - typing-extensions

test:
  imports:
    - h3pandas
    - h3pandas.util
  commands:
    - pytest tests/
  requires:
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/DahnJ/H3-Pandas
  summary: Integration of H3 and GeoPandas
  license: MIT
  license_file: LICENSE
  doc_url: https://h3-pandas.readthedocs.io/en/latest/
  dev_url: https://github.com/DahnJ/H3-Pandas

extra:
  recipe-maintainers:
    - DahnJ
