{% set name = "h3pandas" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/h3pandas-{{ version }}.tar.gz
  sha256: 96c9071299df343a844714b90b06da216dc47b6e23067a2d7292d60790dabd27

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64
    - wheel
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.9
    - geopandas
    - numpy
    - pandas
    - shapely
    - h3-py >=4
    - typing_extensions

test:
  imports:
    - h3pandas
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Integration of H3 and GeoPandas
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DahnJ
